
server:
  port: 7090
spring.datasource.url: jdbc:mysql://100.70.91.43:3308/apollo_config?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: uisread
spring.datasource.password: ?LWm4vDQw8X!,
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
      show-sql: true #打印执行的sql语句
