
server:
  port: 7090
spring.datasource.url: jdbc:mysql://100.77.21.6:3308/apollo_config?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: configopr
spring.datasource.password: Bi#e8y3k
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
      show-sql: true #打印执行的sql语句
