spring:
  application:
    name: apollo-adminservice
  profiles:
    active: dev

ctrip:
  appid: 100003172
  

  
logging:
  file: /app/logs/apollo-adminservice.log
jpa:
    hibernate:
      show-sql: true #打印执行的sql语句
