spring:
  application:
    name: apollo-adminservice
  profiles:
    active: uat

ctrip:
  appid: 100003172
  

  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
jpa:
    hibernate:
      show-sql: true #打印执行的sql语句
