

server:
  port: 80
spring.datasource.url: jdbc:mysql://100.69.76.27:3308/apollo_config?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: uisread
spring.datasource.password: ?LWm4vDQw8X!,
spring.datasource.driver-class-name: com.mysql.jdbc.Driver